"""DiscoverChat configuration — one place for every knob (WP-D5).

Three rules this file exists to keep:

1. **The embedding pin is not re-declared here.** It is imported from
   `phase5d_retrieval_corpus`, which built the corpus, and then CHECKED against
   the stamp the build wrote. A corpus embedded under one pin can never be
   served under another, and the failure is loud. Re-declaring the pin would be
   the drift D17 exists to prevent.

2. **The prose model is `discover_config`'s, never a constant of our own**
   (D42 ruling 6 / D17). Same for the completion budget.

3. **The retrieval thresholds are KNOBS, not buried constants** (D5.1). They
   are the numbers the operator ratifies at D5.3, so they carry their
   provisional status in their names and in this comment, and every one is
   overridable by environment variable without a code change.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
INSIGHTS_SRC = REPO / "Insights" / "src"
ASK_DIR = REPO / "Ask"
METAINSIGHTS = REPO / "Insights" / "metainsights"

for path in (str(INSIGHTS_SRC), str(ASK_DIR)):
    if path not in sys.path:
        sys.path.insert(0, path)

# ── The pins, imported from where they were decided ──────────────────────────
from phase5d_retrieval_corpus import (            # noqa: E402
    EMBED_MODEL, EMBED_DIMS, QUERY_INSTRUCTION, Embedder,
    embedding_pin, pin_fingerprint,
)
from discover_config import (                     # noqa: E402
    DISCOVER_PROSE_MODEL, DISCOVER_MAX_COMPLETION_TOKENS,
)

CORPUS_PATH = METAINSIGHTS / "retrieval_corpus.json"
VECTORS_PATH = METAINSIGHTS / "retrieval_corpus.npy"
STAMP_PATH = METAINSIGHTS / "retrieval_corpus_stamp.json"

# The WP-D6 decomposition sidecar. Retrieved through the same machinery, ranked
# by the same score, and never privileged over a finding (D6.1).
DECOMPOSE_CORPUS_PATH = METAINSIGHTS / "decompose_corpus.json"
DECOMPOSE_VECTORS_PATH = METAINSIGHTS / "decompose_corpus.npy"
DECOMPOSE_STAMP_PATH = METAINSIGHTS / "decompose_corpus_stamp.json"

# The sidecar is a large BUILD OUTPUT (36,218 records, ~310 MB with vectors),
# regenerated by `python Insights/src/phase5f_decompose.py`. The service loads
# it when it is present and runs without it when it is not, because a mirror
# that has not built it yet is a normal state and a hard failure there would
# make the findings half of the product unrunnable too. What is NOT tolerated is
# a sidecar embedded under a different pin -- `assert_pin_matches_corpus`
# refuses that outright, for the reason it refuses it on the findings corpus.
USE_DECOMPOSE = os.getenv("DISCOVERCHAT_USE_DECOMPOSE", "1") not in (
    "0", "", "false", "False")

ASK_DB_PATH = ASK_DIR / "data" / "panchayat_1.duckdb"

DATA_QUERY_EXPANSION = HERE / "query_expansion.json"
DATA_MEASURE_KEYWORDS = HERE / "measure_keywords.json"
DATA_DECOMPOSE_TRIGGERS = HERE / "decompose_triggers.json"

# ── The generative models ────────────────────────────────────────────────────
WRITER_MODEL = DISCOVER_PROSE_MODEL                     # D17 pin, via discover_config
WRITER_MAX_COMPLETION = DISCOVER_MAX_COMPLETION_TOKENS  # D17 budget

# WP-D4 T4 asks for a DIFFERENT model from the writer. Changed from `gpt-5.5`
# to `gpt-5.6-luna` on 2026-09-01 on the operator's instruction, for cost --
# and `luna` is a SIBLING of the writer `gpt-5.6-sol`, not a different
# generation, so the independence T4 was built on is materially weaker here.
# The full rationale and the reopened-gate note live in
# Insights/src/insight_prose_config.py; this pin follows it deliberately so the
# chat path and the build step are judged by the same model.
# Same vendor remains the disclosed limitation: Insights/.env serves one
# completion vendor, so a cross-vendor judge needs a new credential.
VERIFIER_MODEL = os.getenv("DISCOVERCHAT_VERIFIER_MODEL", "gpt-5.6-luna")

# 9,000, NOT WP-D4's 4,000, and the difference was measured rather than guessed.
# The trial's ceiling was sized for one rewritten finding. This verifier reads a
# whole answer -- as many as twelve findings plus the writer's context -- and
# must map every factual claim to a source line. At 4,000 it starved on 4 of 6
# calls: `finish_reason='length'`, 4,000 completion tokens spent entirely on
# reasoning, empty string returned, no error. That is the exact failure D17's
# budget note describes and the exact failure D43's retry-on-empty was added
# for -- and the retry could not help, because the second attempt starved too.
# The two calls that DID return used 1,305 and 1,400 tokens, so the budget is
# not marginal at 9,000; it was simply wrong at 4,000.
VERIFIER_MAX_COMPLETION = int(os.getenv("DISCOVERCHAT_VERIFIER_TOKENS", "9000"))

# The classifier is a small, cheap routing decision, logged per turn (D5.2).
#
# WP-D7 D7.0: `gpt-5.5` -> a nano, on the operator's ruling, for cost and for
# the ~3 s it takes off every turn. ONE CONSTANT, and the budget is checked
# alongside it (D17), because the two are not independent: a smaller model that
# reasons more can starve at a ceiling the larger one never touched.
#
# THE ID IS NOT THE ONE THE BRIEF NAMED, and that was an operator decision taken
# during execution, not a substitution made here. WPD7's ruling 1 and its
# precondition 4 both name `gpt-5.5-nano`; that id returns 404 `model_not_found`
# and appears nowhere in this account's 124-model list. Precondition 4 says STOP
# rather than substitute, so execution stopped and the operator ruled
# (2026-09-03): use `gpt-5.4-nano`, the nearest available nano, and gate it hard.
#
# `gpt-5.4-nano` is a SIBLING OF THE F1 OFFENDER. Ask's WP-4 found
# `gpt-5.4-mini` returning all-null structured output on ~25% of calls, and this
# is the same generation. That is a reason to watch it, not a reason to refuse
# it -- the four-run gate and the non-empty assertion below are precisely the
# instrument for that failure, and running them on the model most likely to show
# it is the point rather than the problem.
#
# THE F1 LESSON IS THE REASON THIS IS GATED RATHER THAN JUST CHANGED. Ask's
# WP-4 found `gpt-5.4-mini` returning all-null structured output on ~25% of
# calls -- no error, no refusal, just nulls, spending 40-52 reasoning tokens
# where a success spent 80-201. It accounted for 55 of 73 confirmed failures
# and it was invisible for a whole work package, because the caller treated a
# null as "no verdict" and fell back. This module's caller does the same thing
# (`classifier.classify` -> RETRIEVE on an unparseable reply), which is the
# right RUNTIME behaviour and the wrong thing to measure a model by. So the
# gate counts empty and unparseable replies explicitly and fails on one.
#
# REVERSION IS THE ENVIRONMENT VARIABLE, no code change and no redeploy:
#     DISCOVERCHAT_CLASSIFIER_MODEL=gpt-5.5
# Set it in the service environment (Railway: Variables) and restart. The gate
# evidence for nano lives in `DiscoverChat/experiments/classifier_nano_results.json`;
# a different id is unevidenced until that file is rebuilt on it:
#     DISCOVERCHAT_CLASSIFIER_MODEL=<id> python DiscoverChat/experiments/run_classifier_nano.py --repeats 4
CLASSIFIER_MODEL = os.getenv("DISCOVERCHAT_CLASSIFIER_MODEL", "gpt-5.4-nano")
CLASSIFIER_MAX_COMPLETION = int(os.getenv("DISCOVERCHAT_CLASSIFIER_TOKENS", "2000"))

CLASSIFIER_EVIDENCE_PATH = HERE / "experiments" / "classifier_nano_results.json"

# The relevance judge (operator proposal, 2026-09-01). Ruling on up to 100
# findings at once is a large reasoning job, and this WP has already lost two
# calls to a reasoning model spending its whole budget on reasoning and
# returning an empty string. Sized with that in mind, and retried on empty.
JUDGE_MODEL = os.getenv("DISCOVERCHAT_JUDGE_MODEL", "gpt-5.6-sol")
JUDGE_MAX_COMPLETION = int(os.getenv("DISCOVERCHAT_JUDGE_TOKENS", "12000"))

# WP-D9: which judge instruction is in force. "complete" keeps every finding
# that adds distinct information; "minimal" is the pre-D9 "smallest sufficient
# set" and is kept reachable as the reversion (D9.1's decision rule reverts by
# configuration, not by a revert commit). The text of each lives in judge.py.
JUDGE_PROMPT_VARIANT = os.getenv("DISCOVERCHAT_JUDGE_PROMPT", "complete")

# ── The judge is bound to the model it was measured on (WP-D6 D6.2 item 2) ───
# WP-D5 moved the out-of-scope guarantee from arithmetic to a model. A floor
# cannot be talked round; a judge can, and at CANDIDATE_FLOOR=0.50 four of the
# five out-of-scope questions reach it with a non-empty pool, so it is the only
# thing standing between them and a confidently-wrong answer. Its 0.0%
# false-answer rate is therefore a property OF ONE MODEL ID, not of the code,
# and swapping the id silently discards the evidence without changing a line
# that review would notice.
#
# The evidenced id is READ FROM THE EVIDENCE, not restated as a constant here.
# A constant can be edited to match a new model in the same commit that swaps
# it, which is exactly the drift this is meant to catch; the run file can only
# say what was actually measured.
JUDGE_EVIDENCE_PATH = HERE / "experiments" / "judge_arm_results.json"


def evidenced_judge_model() -> tuple:
    """(model id, reference) the out-of-scope evidence was measured on."""
    with open(JUDGE_EVIDENCE_PATH, encoding="utf-8") as fh:
        evidence = json.load(fh)
    reference = (f"DiscoverChat/experiments/judge_arm_results.json "
                 f"({evidence['generated_at']}, false-answer rate "
                 f"{evidence['metrics']['none_false_answer_rate']:.1%} over "
                 f"{sum(1 for q in evidence['questions'] if q['kind'] == 'none')}"
                 f" out-of-scope questions)")
    return evidence["judge_model"], reference


def evidenced_judge_prompt() -> tuple:
    """(prompt sha256, reference) the out-of-scope evidence was measured on.

    WP-D9. The same argument as `evidenced_judge_model`, one level down. The
    0.0% false-answer rate is a property of the model AND the words it was
    given; before D9.0 the gate checked only half of that pair, so the
    instruction could be rewritten -- which is exactly what D9.1 does -- with
    every check staying green and the evidence silently no longer describing
    the running system.

    Read from the evidence, never restated as a constant here, for the reason
    given above: a constant can be edited in the same commit that changes the
    prompt.
    """
    with open(JUDGE_EVIDENCE_PATH, encoding="utf-8") as fh:
        evidence = json.load(fh)
    sha = evidence.get("judge_prompt_sha256")
    variant = evidence.get("judge_prompt_variant", "unrecorded")
    reference = (f"DiscoverChat/experiments/judge_arm_results.json "
                 f"({evidence['generated_at']}, prompt {variant!r})")
    return sha, reference


REQUALIFY_JUDGE_PROMPT = (
    "The judge prompt is qualified by the same battery as the judge model. "
    "After editing it, re-run both and let the run files record the new "
    "hash:\n"
    "    python DiscoverChat/experiments/run_judge_arm.py\n"
    "    python DiscoverChat/experiments/run_decompose_oos.py --repeats 4\n"
    "Both must come back with a 0.0% false-answer rate before the wording is "
    "trusted. To revert instead, set DISCOVERCHAT_JUDGE_PROMPT=minimal."
)


REQUALIFY_JUDGE = (
    "To qualify a different judge, re-run the out-of-scope battery on it and "
    "let the run file record the new id:\n"
    "    DISCOVERCHAT_JUDGE_MODEL=<new-id> python "
    "DiscoverChat/experiments/run_judge_arm.py\n"
    "    DISCOVERCHAT_JUDGE_MODEL=<new-id> python "
    "DiscoverChat/experiments/run_decompose_oos.py --repeats 4\n"
    "The first rewrites judge_arm_results.json, which is what this check reads; "
    "the second repeats it with the decomposition sidecar loaded. Both must "
    "come back with a 0.0% false-answer rate before the id is trusted."
)

MAX_PROMPT_TOKENS = 16000        # WP-D4's ceiling, unchanged

# ── Retrieval knobs — PROVISIONAL until D5.3 ratifies them ───────────────────
# Set from the D5.1 experiment; every one is an env override so the operator can
# move a threshold at the pilot without a code change, and so the D5.3 gate can
# ratify a number rather than a diff.
#
# RELEVANCE_THRESHOLD is a FLOOR, not a top-N (D42 ruling 5). Everything above
# it is the answer; if nothing clears it the bot says the analysis has nothing
# on this. It is never relaxed to manufacture an answer.
RELEVANCE_THRESHOLD = float(os.getenv("DISCOVERCHAT_THRESHOLD", "0.62"))

# --- the judged path (arm D) --------------------------------------------------
# When USE_JUDGE is on, the floor drops to CANDIDATE_FLOOR and an LLM decides
# which of the top CANDIDATE_POOL candidates actually answer the question.
# Measured before building: at 0.50, top 100 after the diversity collapse, all
# 34 place questions in the D5.1 set have a genuinely relevant finding in the
# pool (against 19 of 34 answered under the 0.62 threshold alone), and the
# candidate list costs a median 8,589 tokens against the 16k input cap.
#
# The judge may only REJECT. Nothing below CANDIDATE_FLOOR is ever reachable, so
# D42 ruling 5's floor still stands; what moves is the last step of "is this an
# answer?", from a comparison to a judgement.
USE_JUDGE = os.getenv("DISCOVERCHAT_USE_JUDGE", "1") not in ("0", "", "false", "False")
CANDIDATE_FLOOR = float(os.getenv("DISCOVERCHAT_CANDIDATE_FLOOR", "0.50"))
CANDIDATE_POOL = int(os.getenv("DISCOVERCHAT_CANDIDATE_POOL", "100"))

# The engine-score quality floor. The corpus is wide on purpose (D42 ruling 3):
# candidates that never reached the ranked cut are indexed. This is the knob
# that decides which of them may be SHOWN.
QUALITY_FLOOR = float(os.getenv("DISCOVERCHAT_QUALITY_FLOOR", "0.0"))

# The structural boost, added to cosine. Survives only if D5.1 shows it beats
# cosine alone (D42 ruling 4) — the numbers decide, not the argument.
GEO_BOOST = float(os.getenv("DISCOVERCHAT_GEO_BOOST", "0.06"))
MEASURE_BOOST = float(os.getenv("DISCOVERCHAT_MEASURE_BOOST", "0.03"))
# A finding whose SUBSPACE is the officer's own place is about that place; one
# that merely lists it among 20 members mentions it. Both are hits, weighted apart.
GEO_SUBSPACE_BONUS = float(os.getenv("DISCOVERCHAT_GEO_SUBSPACE_BONUS", "0.02"))

# Above this many findings, the answer is written as consolidated prose rather
# than rendered finding by finding (D42 "presentation adapts to its size").
FULL_RENDER_MAX = int(os.getenv("DISCOVERCHAT_FULL_RENDER_MAX", "4"))
# The hard ceiling on how many findings reach one answer. Not a top-N in the
# sense ruling 5 forbids — the floor still decides membership; this only caps
# how much of a very broad sweep is written out at once, and the answer says so.
ANSWER_CAP = int(os.getenv("DISCOVERCHAT_ANSWER_CAP", "20"))

# ── WP-D7: the verifier leaves the turn (D7.1) ───────────────────────────────
# The inline verifier cost a median 28.7 s of a ~60 s turn (measured over the
# seven logged verify calls in `experiments/logs/calls.jsonl`) and is the single
# largest item in time-to-first-paint. D7.1 turns it OFF for turn prose and
# moves it offline as a sampled audit that reports a drift rate.
#
# THIS IS A CONFIG DEFAULT, NOT A DELETION, and the distinction is the whole
# design: `verifier.py` stays, unchanged, because the audit runs the same
# verifier over the same prose with the same context. Turning this back on
# restores the pre-D7 behaviour exactly:
#     DISCOVERCHAT_INLINE_VERIFY=1
#
# WHAT IS GIVEN UP, STATED PLAINLY. WP-D4 measured what the verifier caught that
# no mechanical check could see: 3 qualitative drifts in 15 packets -- a
# limitation narrowed, a sample-wide total pinned to a subset, a claim about the
# analysis itself. The D7.3 citation check covers NUMBERS, not MEANING, and with
# D7.3's consolidating writer the model now restates findings rather than only
# introducing them, so the class of error the verifier caught is if anything
# more reachable. The offline audit is the only measurement of it. Read its
# drift rate as the price of the latency, and see README "The audit is the only
# check on qualitative drift".
INLINE_VERIFY = os.getenv("DISCOVERCHAT_INLINE_VERIFY", "0") not in (
    "0", "", "false", "False")

# ── WP-D7: the consolidating writer (D7.3) ───────────────────────────────────
# REVISES D42 ruling 6 ("the LLM writes only connective prose"). The writer now
# turns the judge's selected findings into ONE narrative, consolidating
# overlapping findings into a small number of patterns, and the finding
# sentences are no longer printed beneath it -- the hover-to-source citation is
# how an officer reaches the stored sentence (D7.2, ruling 4).
#
# The judge selects a median of 3 findings and at most 6 in the measured set;
# ANSWER_CAP is a ceiling, not a typical size (WP-D9 raised it 12 -> 20). So the writer runs on
# essentially every answer that has findings, which is why the minimum is 1 and
# not FULL_RENDER_MAX. FULL_RENDER_MAX is superseded for the judged path and
# kept only for the threshold/no-model path the offline gate runs on.
CONSOLIDATE = os.getenv("DISCOVERCHAT_CONSOLIDATE", "1") not in (
    "0", "", "false", "False")
CONSOLIDATE_MIN_FINDINGS = int(os.getenv("DISCOVERCHAT_CONSOLIDATE_MIN", "1"))

# ── WP-D7: provenance (D7.2) ─────────────────────────────────────────────────
# Every citation in an answer carries the id and a URL that resolves to the
# stored record. The base is configurable because the service and the front end
# are not on the same origin in production (the Discover tab calls a Railway
# service cross-origin), and a relative URL would resolve against the front
# end's host and 404.
#     DISCOVERCHAT_RECORD_URL_BASE=https://discover-api-production-1154.up.railway.app/record
RECORD_URL_BASE = os.getenv("DISCOVERCHAT_RECORD_URL_BASE", "/record").rstrip("/")


def record_url(finding_id: str) -> str:
    return f"{RECORD_URL_BASE}/{finding_id}"


def load_stamp() -> dict:
    with open(STAMP_PATH, encoding="utf-8") as fh:
        return json.load(fh)


def assert_pin_matches_corpus() -> dict:
    """The corpus was embedded under the pin this process is about to query with.

    Called at service startup and by every test. A silent mismatch would mean
    querying a 1,024-dimension corpus with a 4,096-dimension query, or an
    instructed corpus with an uninstructed query — cases that produce plausible
    nonsense rather than an error.
    """
    if not STAMP_PATH.exists():
        raise SystemExit(
            f"STOP: no retrieval corpus stamp at {STAMP_PATH}. "
            f"Run `python Insights/src/phase5d_retrieval_corpus.py` first (D5.0)."
        )
    stamp = load_stamp()
    if stamp.get("embedding_pin_fingerprint") != pin_fingerprint():
        raise SystemExit(
            "STOP: the corpus was embedded under a different pin than this "
            "process would query with.\n"
            f"  corpus: {json.dumps(stamp.get('embedding_pin'), indent=2)}\n"
            f"  here:   {json.dumps(embedding_pin(), indent=2)}\n"
            "Rebuild the corpus, or restore the pin."
        )
    return stamp


def decompose_stamp() -> dict | None:
    """The sidecar's stamp, pin-checked, or None when it has not been built.

    The two corpora share one vector space and are scored against one query
    vector, so a sidecar embedded under a different pin is not a degraded
    experience -- it is nonsense that looks like an answer, which is exactly
    what `assert_pin_matches_corpus` exists to make impossible. Absent is fine;
    present-and-mismatched is a stop.
    """
    if not (USE_DECOMPOSE and DECOMPOSE_STAMP_PATH.exists()):
        return None
    with open(DECOMPOSE_STAMP_PATH, encoding="utf-8") as fh:
        stamp = json.load(fh)
    if stamp.get("embedding_pin_fingerprint") != pin_fingerprint():
        raise SystemExit(
            "STOP: the decomposition sidecar was embedded under a different "
            "pin than this process would query with.\n"
            f"  sidecar: {json.dumps(stamp.get('embedding_pin'), indent=2)}\n"
            f"  here:    {json.dumps(embedding_pin(), indent=2)}\n"
            "Rebuild it with `python Insights/src/phase5f_decompose.py`."
        )
    return stamp


def run_stamp_line() -> str:
    """'as of <run date>' — on every answer, by D42's presentation rule."""
    stamp = load_stamp()
    date = str(stamp.get("candidate_set_generated_at")
               or stamp.get("source_generated_at", ""))[:10]
    if not date:
        # The corpus stamp always carries the candidate set's own stamp; the
        # feed sidecar is the authority for when the analysis was run.
        with open(METAINSIGHTS / "global_feed_source_set.json", encoding="utf-8") as fh:
            date = json.load(fh)["generated_at"][:10]
    return f"as of {date}"


def knobs() -> dict:
    """Every provisional number, for the report and for the D5.3 ratification."""
    return {
        "relevance_threshold": RELEVANCE_THRESHOLD,
        "quality_floor": QUALITY_FLOOR,
        "geo_boost": GEO_BOOST,
        "measure_boost": MEASURE_BOOST,
        "geo_subspace_bonus": GEO_SUBSPACE_BONUS,
        "full_render_max": FULL_RENDER_MAX,
        "answer_cap": ANSWER_CAP,
        "use_judge": USE_JUDGE,
        "candidate_floor": CANDIDATE_FLOOR,
        "candidate_pool": CANDIDATE_POOL,
        "inline_verify": INLINE_VERIFY,
        "consolidate": CONSOLIDATE,
        "consolidate_min_findings": CONSOLIDATE_MIN_FINDINGS,
        "classifier_model": CLASSIFIER_MODEL,
    }
